version: "3.0" 
services:
   mqtt:
            image: eclipse-mosquitto
            ports: 
               - 1883:1883
            volumes:
               - /tmp/mosquitto.conf:/mosquitto/config/mosquitto.conf
            deploy:
                replicas: 1
   node-mqtt-publisher:
            image: node-mqtt-publisher
            deploy:
                replicas: 5
            depends_on:
                - mqtt

networks:
    default:
        external: true
        name: ds-net
         
