version: "3.0"
services:
   node-mqtt-subscriber:
            image: node-mqtt-subscriber
            environment: 
                - PORT=11232
                - ADDRESS=research.upb.edu
                - TOPIC=upb/ds/class
            deploy:
                replicas: 5
            