version: "3.0" 
services:
   mqtt:
            image: eclipse-mosquitto
            ports: 
               - 1883:1883
            volumes:
               - /tmp/mosquitto.conf:/mosquitto/config/mosquitto.conf
            deploy:
                replicas: 1
                restart_policy:
                      condition: on-failure
                placement: 
                      constraints: [node.role == manager]
   node-mqtt-publisher:
            image: node-mqtt-publisher
            deploy:
                replicas: 5
                placement:
                       constraints: [node.role == manager]
            depends_on:
                - mqtt
   node-mqtt-subscriber:
            image: node-mqtt-subscriber
            environment:
                - PORT=1883
                - ADDRESS=10.1.2.123
                - TOPIC=upb/ds/class
            deploy:
                replicas: 5
                placement:
                      constraints: [node.role == worker]


